//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UGE.Models.DataStructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.AdvertiseEntries = new HashSet<AdvertiseEntry>();
            this.AdvertiseEntries1 = new HashSet<AdvertiseEntry>();
            this.Bookmarks = new HashSet<Bookmark>();
            this.Comments = new HashSet<Comment>();
            this.MistakeQuestions = new HashSet<MistakeQuestion>();
            this.RateMCQs = new HashSet<RateMCQ>();
            this.RateMCQs1 = new HashSet<RateMCQ>();
            this.Ratings = new HashSet<Rating>();
            this.WishLists = new HashSet<WishList>();
        }
    
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string DisplayName { get; set; }
        public string AccountID { get; set; }
        public byte UserRoleID { get; set; }
    
        public virtual ICollection<AdvertiseEntry> AdvertiseEntries { get; set; }
        public virtual ICollection<AdvertiseEntry> AdvertiseEntries1 { get; set; }
        public virtual ICollection<Bookmark> Bookmarks { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<MistakeQuestion> MistakeQuestions { get; set; }
        public virtual ICollection<RateMCQ> RateMCQs { get; set; }
        public virtual ICollection<RateMCQ> RateMCQs1 { get; set; }
        public virtual ICollection<Rating> Ratings { get; set; }
        public virtual UserRole UserRole { get; set; }
        public virtual ICollection<WishList> WishLists { get; set; }
    }
}
