//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models.DataStructure
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class Article
    {
        public Article()
        {
            this.Article1 = new HashSet<Article>();
            this.Article11 = new HashSet<Article>();
            this.ArticleMistakes = new HashSet<ArticleMistake>();
            this.Bookmarks = new HashSet<Bookmark>();
            this.Comments = new HashSet<Comment>();
            this.LinksToDisplays = new HashSet<LinksToDisplay>();
            this.MCQs = new HashSet<MCQ>();
            this.Ratings = new HashSet<Rating>();
            this.WatchedReferences = new HashSet<WatchedReference>();
            this.WatchedReferences1 = new HashSet<WatchedReference>();
            this.WishLists = new HashSet<WishList>();
        }
    
        public long ArticleID { get; set; }
        [DisplayName("Article Name")]
        public string ArticleName { get; set; }
        public string Description { get; set; }
        public Nullable<long> PreviousArticleID { get; set; }
        public Nullable<long> NextArticleID { get; set; }
        public int ChapterID { get; set; }
        public string VideoEmbedLink { get; set; }
        public short Height { get; set; }
        public short Width { get; set; }
        public Nullable<byte> AvgRating { get; set; }
        public string VideoLink { get; set; }
    
        public virtual ICollection<Article> Article1 { get; set; }
        public virtual Article Article2 { get; set; }
        public virtual ICollection<Article> Article11 { get; set; }
        public virtual Article Article3 { get; set; }
        public virtual Chapter Chapter { get; set; }
        public virtual ICollection<ArticleMistake> ArticleMistakes { get; set; }
        public virtual ICollection<Bookmark> Bookmarks { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<LinksToDisplay> LinksToDisplays { get; set; }
        public virtual ICollection<MCQ> MCQs { get; set; }
        public virtual ICollection<Rating> Ratings { get; set; }
        public virtual ICollection<WatchedReference> WatchedReferences { get; set; }
        public virtual ICollection<WatchedReference> WatchedReferences1 { get; set; }
        public virtual ICollection<WishList> WishLists { get; set; }
    }
}
