//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models.DataStructure
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class Chapter
    {
        public Chapter()
        {
            this.Articles = new HashSet<Article>();
            this.LinksToDisplays = new HashSet<LinksToDisplay>();
        }
    
        public int ChapterID { get; set; }
        public int BookID { get; set; }
        [DisplayName("Topic Name")]
        public string TopicName { get; set; }
        public int TotalArticles { get; set; }
        public long MasterArticleID { get; set; }
    
        public virtual ICollection<Article> Articles { get; set; }
        public virtual Book Book { get; set; }
        public virtual ICollection<LinksToDisplay> LinksToDisplays { get; set; }
    }
}
