//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models.DataStructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Link
    {
        public long LinkID { get; set; }
        public string URL { get; set; }
        public long AdvertiseEntryID { get; set; }
    
        public virtual AdvertiseEntry AdvertiseEntry { get; set; }
    }
}
