//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models.DataStructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class MistakeQuestion
    {
        public int MistakeQuestionID { get; set; }
        public long QuestionID { get; set; }
        public int SendByUserID { get; set; }
        public bool IsErrorFixed { get; set; }
        public bool IsReceived { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual User User { get; set; }
    }
}
