//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models.DataStructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public Payment()
        {
            this.AdvertiseEntries = new HashSet<AdvertiseEntry>();
        }
    
        public long PaymentID { get; set; }
        public byte PaymentMethodID { get; set; }
        public decimal Paid { get; set; }
        public System.DateTime Dated { get; set; }
        public string CardNumber { get; set; }
        public string AdditionalInformation { get; set; }
    
        public virtual ICollection<AdvertiseEntry> AdvertiseEntries { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
    }
}
