//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models.DataStructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class RateMCQ
    {
        public long RateMCQID { get; set; }
        public int MCQID { get; set; }
        public int UserID { get; set; }
        public byte Rating { get; set; }
    
        public virtual MCQ MCQ { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
