//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models.DataStructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public long RatingID { get; set; }
        public long ArticleID { get; set; }
        public int UserID { get; set; }
        public byte VideoQualtiy { get; set; }
        public byte TechingTechnique { get; set; }
        public byte Mateials { get; set; }
        public double AvgRating { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual User User { get; set; }
    }
}
