//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models.DataStructure
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UGEContext : DbContext
    {
        public UGEContext()
            : base("name=UGEContext")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdvertiseEntry> AdvertiseEntries { get; set; }
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<ArticleMistake> ArticleMistakes { get; set; }
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<Bookmark> Bookmarks { get; set; }
        public virtual DbSet<Chapter> Chapters { get; set; }
        public virtual DbSet<Choice> Choices { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Link> Links { get; set; }
        public virtual DbSet<LinksToDisplay> LinksToDisplays { get; set; }
        public virtual DbSet<MCQ> MCQs { get; set; }
        public virtual DbSet<MistakeQuestion> MistakeQuestions { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<PaymentMethod> PaymentMethods { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<RateMCQ> RateMCQs { get; set; }
        public virtual DbSet<Rating> Ratings { get; set; }
        public virtual DbSet<ReplyAgainstMistake> ReplyAgainstMistakes { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }

        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<WatchedReference> WatchedReferences { get; set; }
        public virtual DbSet<WishList> WishLists { get; set; }
    }
}
